repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        stages: [commit, push]
        files: src/

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        files: src/
        args: ["--quiet"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
        files: src/
        args: ["--disable-error-code",
               "no-redef",
               "--disable-error-code",
               "index",
               "--disable-error-code",
               "import",
               "--disable-error-code",
               "assignment"]